name: CI

on:
  push:
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-gnu

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Build debian package
        run: cargo deb --target x86_64-unknown-linux-gnu

      - name: Upload debian package
        uses: actions/upload-artifact@v4
        with:
          name: debian-package
          path: target/**/*.deb

